### ISSUE TITLE
Outdated info about SANY on README

### ISSUE THREAD

**Issue by bugarela** [tlaplus-community/tlaplus-nvim-plugin#4]
README says:

> Unfortunately SANY and TLC do not currently support Unicode symbols, so if you want to fully parse or model-check your spec you'll need to translate it back to ASCII with the [TLAUC](https://github.com/tlaplus-community/tlauc) command-line tool.

but I've heard SANY now supports it :smile:

**Comment by ahelwer** [comment]
Fixed in 15743ec171e98ad3a2e24f9126b5869aec973d89
